# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80a39a278ef624d65b2f83514a5dfd7b2247c4bc8d5c6269206ea052565ab066bb608acb27d2a3b99d0480de9776112ee012791fd1385ee46b72a1725cf4547d

test:
  secret_key_base: 618c9ed6960ed90a8cda8906b08e95027ff3a20454a01df1df792d2a071bb0a5bcf230018232629ba701c25c1baaa32b06db980399e02c5bb955c64585e28724

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
